include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = AutoPatches

AutoPatches_FILES = ../AutoPatches.mm
AutoPatches_CFLAGS = -fobjc-arc
AutoPatches_LDFLAGS = -L../ -ldobby
AutoPatches_INSTALL_PATH = /usr/lib/DynamicPatches

include $(THEOS_MAKE_PATH)/library.mk
