include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FilzaPatches

FilzaPatches_FILES = ../Patches.mm
FilzaPatches_CFLAGS = -fobjc-arc
FilzaPatches_LDFLAGS = -L../ -ldobby
FilzaPatches_INSTALL_PATH = /usr/lib/DynamicPatches

include $(THEOS_MAKE_PATH)/library.mk
