name: Build DynamicPatches

on:
  workflow_dispatch:
  push:
    branches:
      - auto-fixed-path-runtime

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/roothide/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> "$GITHUB_ENV"

      - name: Build Dobby
        run: |
          git clone --depth 1 https://github.com/jmpews/Dobby.git Dobby-master
          sed -i '' '/^import pipes$/d' Dobby-master/scripts/platform_builder.py
          cmake -S Dobby-master -B Dobby-master/build/arm64 \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_SYSTEM_PROCESSOR=arm64 \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DPlugin.SymbolResolver=ON \
            -DNearBranch=ON
          cmake --build Dobby-master/build/arm64 --target dobby_static --config Release
          cmake -S Dobby-master -B Dobby-master/build/arm64e \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_SYSTEM_PROCESSOR=arm64e \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64e \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DPlugin.SymbolResolver=ON \
            -DNearBranch=ON
          cmake --build Dobby-master/build/arm64e --target dobby_static --config Release
          rm -f ./libdobby.a
          find Dobby-master/build/arm64 -name libdobby.a -type f -exec cp {} ./libdobby-arm64.a \;
          find Dobby-master/build/arm64e -name libdobby.a -type f -exec cp {} ./libdobby-arm64e.a \;
          lipo -create ./libdobby-arm64.a ./libdobby-arm64e.a -output ./libdobby.a
          lipo -info ./libdobby.a
          test -f ./libdobby.a


      - name: Build
        run: |
          export THEOS="$HOME/theos"
          export PATH="$THEOS/bin:$PATH"
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: DynamicPatches-roothide
          path: packages/*.deb
          if-no-files-found: error
